* Use .head(), .tail(), .shape and .columns to explore your DataFrame and
find out the number of rows and columns as well as the column names.

* Look for NaN (not a number) values with .findna() and consider using .dropna() to clean up your DataFrame.

* You can access entire columns of a DataFrame using the square bracket notation: df['column name'] or df[['column name 1', 'column name 2', 'column name 3']]

* You can access individual cells in a DataFrame by chaining square brackets df['column name'][index] or using df['column name'].loc[index]

* The largest and smallest values, as well as their positions, can be found with methods like .max(), .min(), .idxmax() and .idxmin()

* You can sort the DataFrame with .sort_values() and add new columns with .insert()

* To create an Excel Style Pivot Table by grouping entries that belong to a particular category use the .groupby() method

In [29]:
import pandas as pd
df = pd.read_csv('salaries_by_college_major.csv')

In [2]:
df.head()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,41600.0,76800.0,50600.0,136000.0,Business

In [3]:
df.shape

(51, 6)

In [4]:
df.columns

Index(['Undergraduate Major', 'Starting Median Salary',
       'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary',
       'Mid-Career 90th Percentile Salary', 'Group'],
      dtype='object')

In [5]:
df.isna()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,False,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,False,False,False,False,False,False
9,False,False,False,False,False,False
10,False,False,False,False,False,False
11,False,False,False,False,False,False
12,False,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,False,False,False,False,False,False
16,False,False,False,False,False,False
17,False,False,False,False,False,False
18,False,False,False,False,False,False
19,False,False,False,False,False,False
20,False,False,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,False,False,False,False,False
25,False,False,False,False,False,False
26,False,False,False,False,False,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,False,False,False,False
31,False,False,False,False,False,False
32,False,False,False,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,False
43,False,False,False,False,False,False
44,False,False,False,False,False,False
45,False,False,False,False,False,False
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False
50,False,True,True,True,True,True

In [6]:
df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS
50,Source: PayScale Inc.,NaN,NaN,NaN,NaN,NaN

In [7]:
clean_df = df.dropna()
clean_df.tail()

,Undergraduate Major,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
45,Political Science,40800.0,78200.0,41200.0,168000.0,HASS
46,Psychology,35900.0,60400.0,31600.0,127000.0,HASS
47,Religion,34100.0,52000.0,29700.0,96400.0,HASS
48,Sociology,36500.0,58200.0,30700.0,118000.0,HASS
49,Spanish,34000.0,53100.0,31000.0,96400.0,HASS

In [8]:
clean_df['Starting Median Salary']

0     46000.0
1     57700.0
2     42600.0
3     36800.0
4     41600.0
5     35800.0
6     38800.0
7     43000.0
8     63200.0
9     42600.0
10    53900.0
11    38100.0
12    61400.0
13    55900.0
14    53700.0
15    35000.0
16    35900.0
17    50100.0
18    34900.0
19    60900.0
20    38000.0
21    37900.0
22    47900.0
23    39100.0
24    41200.0
25    43500.0
26    35700.0
27    38800.0
28    39200.0
29    37800.0
30    57700.0
31    49100.0
32    36100.0
33    40900.0
34    35600.0
35    49200.0
36    40800.0
37    45400.0
38    57900.0
39    35900.0
40    54200.0
41    39900.0
42    39900.0
43    74300.0
44    50300.0
45    40800.0
46    35900.0
47    34100.0
48    36500.0
49    34000.0
Name: Starting Median Salary, dtype: float64

In [9]:
clean_df['Starting Median Salary'].max()

74300.0

In [10]:
clean_df['Starting Median Salary'].idxmax()

np.int64(43)

In [11]:
clean_df['Undergraduate Major'].loc[43]
# Same result with -
# clean_df['Undergraduate Major'][43]

'Physician Assistant'

In [12]:
clean_df.loc[43]

Undergraduate Major                  Physician Assistant
Starting Median Salary                           74300.0
Mid-Career Median Salary                         91700.0
Mid-Career 10th Percentile Salary                66400.0
Mid-Career 90th Percentile Salary               124000.0
Group                                               STEM
Name: 43, dtype: object

### College Major with the Highest Mid-Career Salary

In [13]:
highest_mid_career_salary = clean_df['Mid-Career Median Salary'].max()
highest_mid_career_major_idx = clean_df['Mid-Career Median Salary'].idxmax()
highest_mid_career_major = clean_df['Undergraduate Major'].loc[highest_mid_career_major_idx]

print(f"The college major with the highest mid-career salary is {highest_mid_career_major} with a median salary of ${highest_mid_career_salary:,.2f}.")

The college major with the highest mid-career salary is Chemical Engineering with a median salary of $107,000.00.

### College Major with the Lowest Starting Salary

In [14]:
lowest_starting_salary = clean_df['Starting Median Salary'].min()
lowest_starting_major_idx = clean_df['Starting Median Salary'].idxmin()
lowest_starting_major = clean_df['Undergraduate Major'].loc[lowest_starting_major_idx]

print(f"The college major with the lowest starting salary is {lowest_starting_major} with a median salary of ${lowest_starting_salary:,.2f}.")

The college major with the lowest starting salary is Spanish with a median salary of $34,000.00.

### College Major with the Lowest Mid-Career Salary

In [15]:
lowest_mid_career_salary = clean_df['Mid-Career Median Salary'].min()
lowest_mid_career_major_idx = clean_df['Mid-Career Median Salary'].idxmin()
lowest_mid_career_major = clean_df['Undergraduate Major'].loc[lowest_mid_career_major_idx]

print(f"The college major with the lowest mid-career salary is {lowest_mid_career_major} with a median salary of ${lowest_mid_career_salary:,.2f}.")

The college major with the lowest mid-career salary is Education with a median salary of $52,000.00.

In [16]:
clean_df.loc[clean_df['Mid-Career Median Salary'].idxmin()]

Undergraduate Major                  Education
Starting Median Salary                 34900.0
Mid-Career Median Salary               52000.0
Mid-Career 10th Percentile Salary      29300.0
Mid-Career 90th Percentile Salary     102000.0
Group                                     HASS
Name: 18, dtype: object

In [19]:
spread_col = clean_df['Mid-Career 90th Percentile Salary']
clean_df.insert(1, 'Spread', spread_col)
clean_df.head()

,Undergraduate Major,Spread,spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary,Group
0,Accounting,152000.0,152000.0,46000.0,77100.0,42200.0,152000.0,Business
1,Aerospace Engineering,161000.0,161000.0,57700.0,101000.0,64300.0,161000.0,STEM
2,Agriculture,150000.0,150000.0,42600.0,71900.0,36300.0,150000.0,Business
3,Anthropology,138000.0,138000.0,36800.0,61500.0,33800.0,138000.0,HASS
4,Architecture,136000.0,136000.0,41600.0,76800.0,50600.0,136000.0,Business

In [20]:
low_risk = clean_df.sort_values('Spread')
low_risk[['Undergraduate Major', 'Spread']].head()

           Undergraduate Major    Spread
49                     Spanish   96400.0
47                    Religion   96400.0
40                     Nursing   98300.0
41                   Nutrition   99200.0
27  Health Care Administration  101000.0

In [21]:
# Majors with the Highest Potential
highest_potential = clean_df.sort_values('Mid-Career 90th Percentile Salary', ascending = False)
highest_potential[['Undergraduate Major', 'Mid-Career 90th Percentile Salary']].head()

     Undergraduate Major  Mid-Career 90th Percentile Salary
17             Economics                           210000.0
22               Finance                           195000.0
8   Chemical Engineering                           194000.0
37                  Math                           183000.0
44               Physics                           178000.0

In [22]:
# Majors with the Greatest Spread in Salaries
highest_spread = clean_df.sort_values('Spread', ascending=False)
highest_spread[['Undergraduate Major', 'Spread']].head()

     Undergraduate Major    Spread
17             Economics  210000.0
22               Finance  195000.0
8   Chemical Engineering  194000.0
37                  Math  183000.0
44               Physics  178000.0

In [23]:
clean_df.groupby('Group').count()

,Undergraduate Major,Spread,spread,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,,,,
Business,12,12,12,12,12,12,12
HASS,22,22,22,22,22,22,22
STEM,16,16,16,16,16,16,16

In [27]:
clean_df.groupby('Group')[['Starting Median Salary', 'Mid-Career Median Salary', 'Mid-Career 10th Percentile Salary', 'Mid-Career 90th Percentile Salary']].mean()

,Starting Median Salary,Mid-Career Median Salary,Mid-Career 10th Percentile Salary,Mid-Career 90th Percentile Salary
Group,,,,
Business,"44,633.33","75,083.33","43,566.67","147,525.00"
HASS,"37,186.36","62,968.18","34,145.45","129,363.64"
STEM,"53,862.50","90,812.50","56,025.00","157,625.00"

In [28]:
pd.options.display.float_format = '{:,.2f}'.format